- name: create inventory file for ips
  vars:
    vm_name: "{{ preappend_host_name }}{{ outer_item.name }}{{ '%02x' |format(inner_item) }}"
    vm_group: "{{ outer_item.cluster_group }}"
  shell: |
     echo "$(ping -c1 {{ vm_name }}.{{ domain }} | sed -nE 's/^PING[^(]+\(([^)]+)\).*/\1/p'), {{ vm_name }}"
  failed_when: "'service not known' in ip_address.stderr"
  register: ip_address
  loop: "{{ range(1, outer_item.qty|int +1)|list }}"
  loop_control:
    loop_var: inner_item
    label: "{{ vm_name }}"
  when: vm_group == 'nodes' or vm_group == 'infra'
  ignore_errors: yes

- name: Ping result
  debug: "var=ip_address.results"
  ignore_errors: yes

- name: "Failed to ping {{ ip_address.results[0].stdout }}.{{ domain }} "
  fail:
    msg: "ERROR: {{  ip_address.results[0].stderr }} "
  when: ip_address is failed
    #("'Name or service not known' in ip_address.results[0].stderr" and   ip_address.results[0].stderr != "")

- include_tasks: save_ip.yml
  with_items: "{{ ip_address.results }}"
  loop_control:
    loop_var: ip_addr
