- name: create list of masters
  vars:
    vm_name: "{{ preappend_host_name }}{{ outer_item.name }}{{ '%02x' |format(inner_item) }}"
    vm_group: "{{ outer_item.cluster_group }}"
  set_fact:
    masters: "{{ masters|default([]) + [ vm_name ] }}"
  loop: "{{ range(1, outer_item.qty|int +1)|list }}"
  loop_control:
    loop_var: inner_item
    label: "{{ vm_name }}"
  when: vm_group == 'masters'

- name: create list of nodes
  vars:
    vm_name: "{{ preappend_host_name }}{{ outer_item.name }}{{ '%02x' |format(inner_item) }}"
    vm_group: "{{ outer_item.cluster_group }}"
  set_fact:
    nodes: "{{ nodes|default([]) + [ vm_name ] }}"
  loop: "{{ range(1, outer_item.qty|int +1)|list }}"
  loop_control:
    loop_var: inner_item
    label: "{{ vm_name }}"
  when: vm_group == 'nodes'

- name: create list of computes
  vars:
    vm_name: "{{ preappend_host_name }}{{ outer_item.name }}{{ '%02x' |format(inner_item) }}"
    vm_group: "{{ outer_item.cluster_group }}"
  set_fact:
    nodes: "{{ nodes|default([]) + [ vm_name ] }}"
  loop: "{{ range(1, outer_item.qty|int +1)|list }}"
  loop_control:
    loop_var: inner_item
    label: "{{ vm_name }}"
  when: vm_group == 'computes'

- name: create list of lbs
  vars:
    vm_name: "{{ preappend_host_name }}{{ outer_item.name }}{{ '%02x' |format(inner_item) }}"
    vm_group: "{{ outer_item.cluster_group }}"
  set_fact:
    lbs: "{{ lbs|default([]) + [ vm_name ] }}"
  loop: "{{ range(1, outer_item.qty|int +1)|list }}"
  loop_control:
    loop_var: inner_item
    label: "{{ vm_name }}"
  when: vm_group == 'lbs'

- name: create list of all nodes
  vars:
    vm_name: "{{ preappend_host_name }}{{ outer_item.name }}{{ '%02x' |format(inner_item) }}"
    vm_group: "{{ outer_item.cluster_group }}"
  set_fact:
    all_nodes: "{{ all_nodes|default([]) + [ vm_name ] }}"
  loop: "{{ range(1, outer_item.qty|int +1)|list }}"
  loop_control:
    loop_var: inner_item
    label: "{{ vm_name }}"
