---
- name: loop through vm types
  include_tasks: inventory_template_outer.yml
  loop: "{{ instances }}"
  loop_control:
    loop_var: outer_item
    label: outer_item.name

- name: show masters
  debug:
    var: masters
  when: masters is defined

- name: show nodes
  debug:
    var: nodes
  when: nodes is defined

- name: show lb
  debug:
    var: lbs
  when: lbs is defined

- name: show computes
  debug:
    var: computes
  when: computes is defined

- name: show nodes
  debug:
    var: all_nodes

- name: loop through vm types
  include_tasks: collect_ips.yml
  loop: "{{ instances }}"
  loop_control:
    loop_var: outer_item
    label: outer_item.name

- name: show gluster_nodes
  debug:
    var: gluster_nodes

- name: deploy openshift template
  template:
    src: templates/inventory.3.11.rhel.gluster
    dest: "{{ inventory_destination }}"
