- name: update masters inventory
  vars:
    inventory_group: "{{ outer_item.inventory_group }}"
    name: "ocp-{{ outer_item.name }}{{ '%02x' |format(inner_item) }}"
  lineinfile:
    path: "{{ inventory_dir }}/{{ group }}"
    #line: "{{ name }}"
    line: "{{ name }}   ansible_host={{ hostvars[name].ansible_host }} ansible_user={{ admin_user }}"
    regexp: "^{{ name }}.*"
    #regexp: "^{{ name }}\\d+"
    insertafter: "'^\\[{{ group }}\\]'"
    state: present
    #firstmatch: yes
  loop: "{{ range(1, outer_item.qty|int +1)|list }}"
  loop_control:
    loop_var: inner_item
    label: "adding {{ name }} to {{ inventory_group }} group"
  when: group == inventory_group
