- name: create masters group file
  file:
    path: "{{ inventory_dir }}/{{ item }}"
    state: touch
  loop:
    - masters
    - nodes
    - dns
    - lbs

- name: create masters group section
  lineinfile:
    path: "{{ inventory_dir }}/masters"
    line: '[masters]'
    state: present

- name: adding host to master group
  vars:
    group: masters
  include_tasks: vms_inventory_outer.yml

- name: create nodes section
  lineinfile:
    path: "{{ inventory_dir }}/nodes"
    line: '[nodes]'
    state: present

- name: adding host to nodes group
  vars:
    group: nodes
  include_tasks: vms_inventory_outer.yml

- name: create lb group section
  lineinfile:
    path: "{{ inventory_dir }}/lbs"
    line: '[lb]'
    state: present

- name: adding host to lb group
  vars:
    group: lbs
  include_tasks: vms_inventory_outer.yml
